import { ApiProperty, ApiPropertyOptional, PartialType } from '@nestjs/swagger';
import { DiscountType } from '@prisma/client';
import { Type } from 'class-transformer';
import { IsArray, IsBoolean, IsDateString, IsEnum, IsInt, IsNumber, IsOptional, IsString, Max, Min, MinLength, ValidateNested } from 'class-validator';

export class StudentQueryDto { @ApiPropertyOptional() @IsOptional() @IsString() search?: string; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(1) page = 1; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(100) limit = 20; }
export class AdminReasonDto { @ApiProperty() @IsString() @MinLength(3) reason!: string; }
export class AdminResetPasswordDto { @ApiProperty() @IsString() @MinLength(8) password!: string; @ApiProperty() @IsString() @MinLength(3) reason!: string; }
export class FinanceExpenseDto { @ApiProperty() @IsString() @MinLength(1) id!: string; @ApiProperty() @IsString() @MinLength(1) title!: string; @ApiProperty() @Type(() => Number) @IsNumber({ maxDecimalPlaces: 0 }) @Min(0) amount!: number; @ApiProperty() @IsString() category!: string; @ApiPropertyOptional() @IsOptional() @IsString() note?: string; @ApiProperty() @IsDateString() date!: string; }
export class UpdateSettingsDto { @ApiPropertyOptional() @IsOptional() @IsString() canteenName?: string; @ApiPropertyOptional() @IsOptional() @IsString() logoUrl?: string; @ApiPropertyOptional({ type: [FinanceExpenseDto] }) @IsOptional() @IsArray() @ValidateNested({ each: true }) @Type(() => FinanceExpenseDto) expenses?: FinanceExpenseDto[]; @ApiPropertyOptional() @IsOptional() @IsString() address?: string; @ApiPropertyOptional() @IsOptional() @IsString() contactInformation?: string; @ApiPropertyOptional() @IsOptional() @IsString() openingTime?: string; @ApiPropertyOptional() @IsOptional() @IsString() closingTime?: string; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(5) defaultPickupInterval?: number; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(1) pointValueVnd?: number; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(0) @Max(100) comboDiscountPercent?: number; }
export class CreateCouponDto { @ApiProperty() @IsString() code!: string; @ApiProperty() @IsString() name!: string; @ApiProperty() @IsString() description!: string; @ApiProperty({ enum: DiscountType }) @IsEnum(DiscountType) type!: DiscountType; @ApiProperty() @Type(() => Number) @IsInt() @Min(0) discountValue!: number; @ApiProperty() @Type(() => Number) @IsInt() @Min(0) minimumOrderValue!: number; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() maximumDiscount?: number; @ApiProperty() @IsDateString() startAt!: string; @ApiProperty() @IsDateString() expireAt!: string; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() usageLimit?: number; @ApiProperty() @Type(() => Number) @IsInt() @Min(1) perStudentLimit!: number; @ApiPropertyOptional() @IsOptional() @Type(() => Boolean) @IsBoolean() requiresCombo?: boolean; }
export class UpdateCouponDto extends PartialType(CreateCouponDto) {}
export class CreateVoucherDto { @ApiProperty() @IsString() code!: string; @ApiProperty() @IsString() name!: string; @ApiProperty() @IsString() description!: string; @ApiProperty({ enum: DiscountType }) @IsEnum(DiscountType) discountType!: DiscountType; @ApiProperty() @Type(() => Number) @IsInt() @Min(0) discountValue!: number; @ApiProperty() @Type(() => Number) @IsInt() @Min(0) requiredPoints!: number; @ApiProperty() @Type(() => Number) @IsInt() @Min(1) totalQuantity!: number; @ApiProperty() @Type(() => Number) @IsInt() @Min(0) minimumOrderValue!: number; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(0) maximumDiscount?: number; @ApiProperty() @IsDateString() startAt!: string; @ApiProperty() @IsDateString() expireAt!: string; @ApiProperty() @Type(() => Number) @IsInt() @Min(1) perStudentLimit!: number; }
export class UpdateVoucherDto extends PartialType(CreateVoucherDto) { @ApiPropertyOptional() @IsOptional() @Type(() => Boolean) @IsBoolean() isActive?: boolean; }
