services:
  - type: web
    name: canteenpn-api
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: WEB_ORIGIN
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_TTL
        value: 15m
      - key: JWT_REFRESH_TTL_DAYS
        value: 30
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SEED_DEMO_PASSWORD
        sync: false
