'use client';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Banknote, Check, RefreshCw, X } from 'lucide-react';
import Link from 'next/link';
import { useCallback, useMemo, useState } from 'react';
import { EmptyState, LoadingState } from '@/components/loading-state'; import { StatusBadge } from '@/components/status-badge'; import { apiRequest, authHeaders, formatDateTime, formatMoney } from '@/lib/api'; import { useAuthStore } from '@/lib/auth-store'; import { useRealtime } from '@/lib/use-realtime';
type Order={id:string;orderCode:string;status:string;paymentMethod:string;paymentStatus:string;totalAmount:number;createdAt:string;studentProfile:{studentDirectory:{fullName:string;studentCode:string}};items:{id:string;productNameSnapshot:string;quantity:number}[]};
const realtimeEvents=['order:new','order:accepted','order:rejected','order:ready','order:cancelled'];
const statusFilters = [
  { value: 'ALL', label: 'Tất cả' },
  { value: 'PENDING', label: 'Chờ xác nhận' },
  { value: 'ACCEPTED', label: 'Đã nhận' },
  { value: 'READY', label: 'Sẵn sàng' },
  { value: 'COMPLETED', label: 'Hoàn tất' },
  { value: 'REJECTED', label: 'Từ chối' },
] as const;
export function CashierBoard(){const token=useAuthStore(s=>s.accessToken);const qc=useQueryClient();const [status,setStatus]=useState('ALL');const [message,setMessage]=useState('');const q=useQuery({queryKey:['cashier-orders'],queryFn:()=>apiRequest<Order[]>('/cashier/orders',{headers:authHeaders(token)}),enabled:!!token,refetchInterval:20_000});const refresh=useCallback(()=>{qc.invalidateQueries({queryKey:['cashier-orders']})},[qc]);useRealtime(realtimeEvents,refresh);const action=useMutation({mutationFn:({id,kind}:{id:string;kind:string})=>apiRequest(`/cashier/orders/${id}/${kind}`,{method:'POST',headers:authHeaders(token),body:kind==='reject'?JSON.stringify({reason:'Thu ngân từ chối do không thể phục vụ'}):undefined}),onSuccess:()=>{setMessage('Đã cập nhật đơn hàng.');refresh()},onError:(e:any)=>setMessage(e.message??'Không thể cập nhật')});const rows=useMemo(()=>q.data?.filter(o=>status==='ALL'||o.status===status)??[],[q.data,status]);if(q.isLoading)return <LoadingState/>;return <div className="space-y-6">{message&&<p className="rounded-2xl bg-brand-50 p-3 text-sm font-bold text-brand-700 dark:bg-brand-900/30">{message}</p>}<div className="flex flex-wrap gap-2">{statusFilters.map(({value,label})=><button key={value} onClick={()=>setStatus(value)} className={status===value?'button-primary':'button-secondary'}>{label}</button>)}<button onClick={()=>refresh()} className="button-secondary ml-auto"><RefreshCw size={17}/>Làm mới</button></div>{rows.length?<div className="grid gap-4 xl:grid-cols-2">{rows.map(order=><article key={order.id} className="surface rounded-3xl p-5"><div className="flex items-start justify-between"><div><Link href={`/cashier/orders/${order.id}`} className="text-lg font-black hover:text-brand-600">{order.orderCode}</Link><p className="mt-1 text-sm text-[color:var(--muted)]">{order.studentProfile.studentDirectory.fullName} · {formatDateTime(order.createdAt)}</p></div><StatusBadge value={order.status}/></div><div className="my-4 border-t"/><div className="space-y-1 text-sm">{order.items.slice(0,3).map(i=><p key={i.id}>{i.quantity}× {i.productNameSnapshot}</p>)}</div><div className="mt-5 flex flex-wrap items-center gap-2"><strong className="mr-auto text-lg">{formatMoney(order.totalAmount)}</strong>{order.status==='PENDING'&&<><button onClick={()=>action.mutate({id:order.id,kind:'accept'})} className="button-primary"><Check size={17}/>Nhận đơn</button><button onClick={()=>action.mutate({id:order.id,kind:'reject'})} className="button-secondary text-red-600"><X size={17}/>Từ chối</button></>}{order.paymentMethod==='CASH'&&order.paymentStatus==='PENDING'&&<button onClick={()=>action.mutate({id:order.id,kind:'confirm-cash'})} className="button-secondary"><Banknote size={17}/>Đã thu tiền</button>}</div></article>)}</div>:<EmptyState title="Không có đơn ở trạng thái này"/>}</div>}
