'use client';
import { useQuery } from '@tanstack/react-query';
import { BarChart3, ChefHat, CircleDollarSign, ClipboardList, TriangleAlert, Users } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { apiRequest, authHeaders, formatMoney } from '@/lib/api';
import { useAuthStore } from '@/lib/auth-store';
import { LoadingState } from '@/components/loading-state';
import { StatusBadge } from '@/components/status-badge';

type Dashboard = { summary: Record<string,number>; charts:{ revenueByDay:{date:string;value:number}[] }; recentOrders:{id:string;orderCode:string;status:string;totalAmount:number;studentProfile:{studentDirectory:{fullName:string}}}[]; lowStock:{id:string;name:string;currentQuantity:string;reservedQuantity:string;unit:string;lowStockThreshold:string}[] };
const cards = [['revenueToday','Doanh thu hôm nay',CircleDollarSign],['ordersToday','Đơn hôm nay',ClipboardList],['preparingOrders','Đang chế biến',ChefHat],['activeStudents','Sinh viên hoạt động',Users],['lowStockIngredients','Sắp hết hàng',TriangleAlert]] as const;
export function AdminDashboard() { const token=useAuthStore(s=>s.accessToken); const query=useQuery({queryKey:['admin-dashboard'],queryFn:()=>apiRequest<Dashboard>('/admin/dashboard',{headers:authHeaders(token)}),enabled:!!token,refetchInterval:30_000}); if(query.isLoading||!query.data)return <LoadingState/>; const d=query.data; return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([key,label,Icon])=><article key={key} className="surface rounded-3xl p-5"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-brand-50 text-brand-700 dark:bg-brand-900/30"><Icon size={21}/></span><BarChart3 size={17} className="text-[color:var(--muted)]"/></div><p className="mt-5 text-sm text-[color:var(--muted)]">{label}</p><p className="mt-1 text-2xl font-black">{key==='revenueToday'?formatMoney(d.summary[key]):d.summary[key].toLocaleString('vi-VN')}</p></article>)}</div><div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><section className="surface rounded-3xl p-6"><h2 className="text-xl font-black">Doanh thu 30 ngày</h2><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={d.charts.revenueByDay}><defs><linearGradient id="revenue" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#008c68" stopOpacity={.35}/><stop offset="95%" stopColor="#008c68" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis tickFormatter={v=>`${Math.round(v/1000)}k`} tick={{fontSize:11}}/><Tooltip formatter={v=>formatMoney(Number(v))}/><Area type="monotone" dataKey="value" stroke="#008c68" fill="url(#revenue)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></section><section className="surface rounded-3xl p-6"><h2 className="text-xl font-black">Cảnh báo tồn kho</h2><div className="mt-5 space-y-3">{d.lowStock.slice(0,7).map(item=><div key={item.id} className="flex items-center justify-between rounded-2xl border p-3"><div><p className="font-bold">{item.name}</p><p className="text-xs text-[color:var(--muted)]">Khả dụng: {(Number(item.currentQuantity)-Number(item.reservedQuantity)).toFixed(1)} {item.unit}</p></div><TriangleAlert size={18} className="text-amber-500"/></div>)}</div></section></div><section className="surface rounded-3xl p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-black">Đơn gần đây</h2></div><div className="table-shell"><table className="data-table"><thead><tr><th>Mã đơn</th><th>Sinh viên</th><th>Trạng thái</th><th className="text-right">Tổng tiền</th></tr></thead><tbody>{d.recentOrders.map(order=><tr key={order.id}><td className="font-bold">{order.orderCode}</td><td>{order.studentProfile.studentDirectory.fullName}</td><td><StatusBadge value={order.status}/></td><td className="text-right font-bold">{formatMoney(order.totalAmount)}</td></tr>)}</tbody></table></div></section></div>; }
