'use client';
import { useQuery } from '@tanstack/react-query';
import { Download, RefreshCw, Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import { EmptyState, LoadingState } from '@/components/loading-state';
import { StatusBadge } from '@/components/status-badge';
import { apiRequest, authHeaders, formatDateTime, formatMoney, formatQuantity } from '@/lib/api';
import { useAuthStore } from '@/lib/auth-store';

type AnyRow = Record<string, any>;
const config: Record<string,{ endpoint:string; description:string }> = {
  orders:{endpoint:'/admin/orders',description:'Theo dõi và kiểm soát toàn bộ vòng đời đơn.'}, products:{endpoint:'/products?limit=100&available=false',description:'Danh mục món, giá bán và trạng thái phục vụ.'}, categories:{endpoint:'/categories',description:'Nhóm thực đơn hiển thị cho sinh viên.'}, combos:{endpoint:'/combos',description:'Các gói món ưu đãi tự động giảm 10%.'}, inventory:{endpoint:'/admin/ingredients',description:'Tồn thực tế, lượng đang giữ và cảnh báo.'}, ingredients:{endpoint:'/admin/ingredients',description:'Định mức và đơn vị nguyên liệu.'}, suppliers:{endpoint:'/admin/suppliers',description:'Danh bạ đối tác cung ứng.'}, 'stock-receipts':{endpoint:'/admin/stock-receipts',description:'Phiếu nhập và lịch sử xác nhận kho.'}, employees:{endpoint:'/admin/employees',description:'Nhân sự thu ngân và bếp.'}, students:{endpoint:'/admin/students?page=1&limit=100',description:'Danh bạ sinh viên và trạng thái tài khoản.'}, shifts:{endpoint:'/admin/shifts',description:'Lịch phân ca, chống trùng giờ.'}, attendance:{endpoint:'/admin/attendance',description:'Giờ vào/ra và tình trạng chuyên cần.'}, coupons:{endpoint:'/admin/coupons',description:'Mã giảm giá áp dụng khi checkout.'}, vouchers:{endpoint:'/admin/vouchers',description:'Voucher đổi bằng điểm CanteenPN.'}, reviews:{endpoint:'/admin/reviews',description:'Kiểm duyệt đánh giá từ sinh viên.'}, 'wallet-transactions':{endpoint:'/admin/wallet-transactions',description:'Sổ cái ví điện tử không thể chỉnh sửa.'}
};
config.products.endpoint = '/admin/products';
config.categories.endpoint = '/admin/categories';
config.combos.endpoint = '/admin/combos';
const labels:Record<string,string>={orders:'Đơn hàng',products:'Sản phẩm',categories:'Danh mục',combos:'Combo',inventory:'Tồn kho',ingredients:'Nguyên liệu',suppliers:'Nhà cung cấp','stock-receipts':'Phiếu nhập kho',employees:'Nhân viên',students:'Sinh viên',shifts:'Ca làm',attendance:'Chấm công',coupons:'Coupon',vouchers:'Voucher',reviews:'Đánh giá','wallet-transactions':'Giao dịch ví'};
function display(key:string,value:any){ if(value===null||value===undefined)return '—'; if(['currentQuantity','reservedQuantity','lowStockThreshold','reorderThreshold','quantity'].includes(key))return formatQuantity(value); if(key.toLowerCase().includes('amount')||key.includes('Price')||key==='totalCost'||key==='balanceAfter')return formatMoney(Number(value)); if(key.endsWith('At')||key==='date')return formatDateTime(value); if(typeof value==='boolean')return value?'Có':'Không'; if(typeof value==='object') { const likely=value.fullName??value.name??value.email??value.studentDirectory?.fullName??value.orderCode; return likely??`${Array.isArray(value)?value.length:Object.keys(value).length} mục`; } return String(value); }
function keysFor(rows:AnyRow[]){ const preferred=['orderCode','studentCode','employeeCode','receiptCode','code','name','fullName','email','status','workRole','currentQuantity','reservedQuantity','unit','basePrice','totalAmount','amount','balanceAfter','rating','date','startTime','endTime','createdAt']; const all=[...new Set(rows.flatMap(r=>Object.keys(r)))]; return preferred.filter(k=>all.includes(k)).slice(0,6).concat(all.filter(k=>!preferred.includes(k)&&!['id','updatedAt','deletedAt','passwordHash'].includes(k)).slice(0,Math.max(0,6-preferred.filter(k=>all.includes(k)).length))); }
export function AdminResource({ resource }: {resource:string}){ const token=useAuthStore(s=>s.accessToken); const [search,setSearch]=useState(''); const setting=config[resource]; const query=useQuery({queryKey:['admin-resource',resource],queryFn:()=>apiRequest<any>(setting.endpoint,{headers:authHeaders(token)}),enabled:!!token&&!!setting}); const rows:AnyRow[]=useMemo(()=>{const raw=query.data?.items??query.data??[];return Array.isArray(raw)?raw:[]},[query.data]); const filtered=rows.filter(row=>JSON.stringify(row).toLowerCase().includes(search.toLowerCase())); const keys=keysFor(rows); if(!setting)return <EmptyState title="Trang không tồn tại"/>; if(query.isLoading)return <LoadingState/>; return <div className="space-y-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Quản lý dữ liệu</p><h2 className="mt-2 text-3xl font-black">{labels[resource]}</h2></div><div className="flex gap-2"><button onClick={()=>query.refetch()} className="button-secondary"><RefreshCw size={17}/> Làm mới</button>{resource==='wallet-transactions'&&<a className="button-primary" href="#"><Download size={17}/> Xuất sổ cái</a>}</div></div><label className="relative block max-w-md"><Search size={17} className="absolute left-4 top-3.5 text-[color:var(--muted)]"/><input className="field pl-11" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm trong dữ liệu hiện tại…"/></label>{filtered.length?<div className="table-shell"><table className="data-table"><thead><tr>{keys.map(k=><th key={k}>{k.replace(/([A-Z])/g,' $1')}</th>)}</tr></thead><tbody>{filtered.map((row,i)=><tr key={row.id??i}>{keys.map(k=><td key={k}>{k==='status'||k==='workRole'?<StatusBadge value={String(row[k])}/>:display(k,row[k])}</td>)}</tr>)}</tbody></table></div>:<EmptyState title="Không có bản ghi phù hợp"/>}</div>; }
