import Link from 'next/link';
import { CheckCircle2, ShieldCheck } from 'lucide-react';

export function AuthShell({ title, description, children, footer }: { title: string; description: string; children: React.ReactNode; footer: React.ReactNode }) {
  return <main className="grid min-h-screen bg-[color:var(--background)] lg:grid-cols-[1fr_1.08fr]">
    <aside className="relative hidden overflow-hidden bg-brand-900 p-12 text-white lg:flex lg:flex-col lg:justify-between xl:p-16"><div className="absolute -left-24 -top-24 h-80 w-80 rounded-full bg-brand-500/20 blur-3xl"/><Link href="/" className="relative flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-[15px] bg-white text-sm font-extrabold text-brand-700">PN</span><span><b className="block text-xl font-extrabold">Canteen<span className="text-brand-500">PN</span></b><small className="text-[9px] font-bold uppercase tracking-wider text-white/60">Ăn ngon · Học tốt</small></span></Link><div className="relative max-w-xl"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-emerald-300">CanteenPN Campus</p><p className="mt-5 text-5xl font-extrabold leading-[1.1] tracking-[-.045em]">Bữa ăn ngon,<br/><span className="text-amber-300">ngày học trọn vẹn.</span></p><p className="mt-6 max-w-lg text-base leading-8 text-emerald-50/70">Đặt trước, nhận nhanh và không bỏ lỡ tiết học tiếp theo.</p><div className="mt-10 flex gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white/10"><CheckCircle2/></span><div><b className="block text-lg">1.200+ sinh viên</b><small className="text-white/55">đang sử dụng CanteenPN mỗi ngày</small></div></div></div><p className="relative text-xs text-white/45">© 2026 CanteenPN · Căng tin Học viện Phụ nữ</p></aside>
    <section className="relative flex items-center justify-center px-5 py-14 sm:px-10"><div className="absolute right-6 top-6"><ShieldCheck className="text-brand-600"/></div><div className="surface w-full max-w-lg rounded-[24px] p-7 sm:p-10"><Link href="/" className="mb-9 inline-flex items-center gap-3 lg:hidden"><span className="grid h-11 w-11 place-items-center rounded-[14px] bg-brand-600 text-sm font-extrabold text-white">PN</span><b className="text-xl">CanteenPN</b></Link><p className="eyebrow">Tài khoản căng tin</p><h1 className="mt-3 text-4xl font-extrabold tracking-[-.045em]">{title}</h1><p className="mt-3 text-sm leading-7 text-[color:var(--muted)]">{description}</p>{children}<div className="mt-7 text-center text-sm">{footer}</div></div></section>
  </main>;
}

