'use client';

import { useMutation, useQuery } from '@tanstack/react-query';
import { Banknote, CheckCircle2, LoaderCircle, QrCode, Wallet } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { apiRequest, type ApiFailure } from '@/lib/api';
import { useAuthStore } from '@/lib/auth-store';

type Quote = { subtotal:number; comboSavings:number; couponDiscount:number; voucherDiscount:number; pointDiscount:number; totalAmount:number; lines:{name:string;quantity:number;lineSubtotal:number}[] };
type OwnedVoucher = { id:string; status:string; serialCode:string; voucher:{name:string;discountType:string;discountValue:number;expireAt:string} };
const money=(value:number)=>new Intl.NumberFormat('vi-VN').format(value)+' ₫';

export function CheckoutClient(){
  const router=useRouter(); const token=useAuthStore(state=>state.accessToken);
  const [form,setForm]=useState({diningType:'TAKEAWAY',pickupType:'ASAP',scheduledPickupAt:'',paymentMethod:'CASH',couponCode:'',studentVoucherId:'',pointsToUse:0,note:''});
  const [quote,setQuote]=useState<Quote>(); const [error,setError]=useState('');
  const vouchers=useQuery({queryKey:['owned-vouchers'],queryFn:()=>apiRequest<OwnedVoucher[]>('/student-vouchers',{headers:{Authorization:`Bearer ${token}`}}),enabled:!!token});
  const discounts={couponCode:form.couponCode||undefined,studentVoucherId:form.studentVoucherId||undefined,pointsToUse:Number(form.pointsToUse)};
  const quoteMutation=useMutation({mutationFn:()=>apiRequest<Quote>('/checkout/quote',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:JSON.stringify(discounts)}),onSuccess:value=>{setQuote(value);setError('')},onError:value=>setError((value as unknown as ApiFailure).message)});
  const orderMutation=useMutation({mutationFn:()=>apiRequest<{id:string}>('/orders',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({...form,scheduledPickupAt:form.pickupType==='SCHEDULED'?new Date(form.scheduledPickupAt).toISOString():undefined,...discounts})}),onSuccess:order=>router.push(`/orders/${order.id}`),onError:value=>setError((value as unknown as ApiFailure).message)});
  if(!token)return <div className="surface rounded-4xl p-8">Vui lòng đăng nhập để thanh toán.</div>;
  const activeVouchers=vouchers.data?.filter(item=>item.status==='ACTIVE'&&new Date(item.voucher.expireAt)>new Date())??[];
  return <div className="grid gap-6 lg:grid-cols-[1fr_380px]">
    <div className="space-y-6">
      <section className="surface rounded-4xl p-6"><h2 className="text-xl font-black">1. Cách dùng món</h2><div className="mt-4 grid grid-cols-2 gap-3">{[['DINE_IN','Dùng tại căng tin'],['TAKEAWAY','Mang đi']].map(([value,label])=><button key={value} onClick={()=>setForm(current=>({...current,diningType:value}))} className={`rounded-2xl border p-4 text-left font-bold ${form.diningType===value?'border-brand-600 bg-brand-50 text-brand-700 dark:bg-brand-900/30':''}`}>{label}</button>)}</div></section>
      <section className="surface rounded-4xl p-6"><h2 className="text-xl font-black">2. Thời gian nhận</h2><div className="mt-4 grid grid-cols-2 gap-3">{[['ASAP','Sớm nhất'],['SCHEDULED','Hẹn giờ']].map(([value,label])=><button key={value} onClick={()=>setForm(current=>({...current,pickupType:value}))} className={`rounded-2xl border p-4 text-left font-bold ${form.pickupType===value?'border-brand-600 bg-brand-50 text-brand-700 dark:bg-brand-900/30':''}`}>{label}</button>)}</div>{form.pickupType==='SCHEDULED'&&<input type="datetime-local" value={form.scheduledPickupAt} onChange={event=>setForm(current=>({...current,scheduledPickupAt:event.target.value}))} className="mt-4 h-12 w-full rounded-2xl border bg-transparent px-4"/>}</section>
      <section className="surface rounded-4xl p-6"><h2 className="text-xl font-black">3. Thanh toán</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{[{value:'CASH',label:'Tiền mặt',icon:Banknote},{value:'VNPAY_QR_MOCK',label:'VNPay QR demo',icon:QrCode},{value:'CANTEEN_WALLET',label:'Ví CanteenPN',icon:Wallet}].map(option=><button key={option.value} onClick={()=>setForm(current=>({...current,paymentMethod:option.value}))} className={`rounded-2xl border p-4 text-left ${form.paymentMethod===option.value?'border-brand-600 bg-brand-50 text-brand-700 dark:bg-brand-900/30':''}`}><option.icon size={22}/><span className="mt-3 block font-bold">{option.label}</span></button>)}</div></section>
      <section className="surface rounded-4xl p-6"><h2 className="text-xl font-black">4. Ưu đãi</h2><div className="mt-4 grid gap-4 sm:grid-cols-3"><label><span className="mb-2 block text-sm font-bold">Mã coupon</span><input value={form.couponCode} onChange={event=>setForm(current=>({...current,couponCode:event.target.value.toUpperCase()}))} className="field" placeholder="WELCOME10"/></label><label><span className="mb-2 block text-sm font-bold">Voucher của bạn</span><select value={form.studentVoucherId} onChange={event=>setForm(current=>({...current,studentVoucherId:event.target.value}))} className="field"><option value="">Không dùng voucher</option>{activeVouchers.map(item=><option key={item.id} value={item.id}>{item.voucher.name} · {item.serialCode}</option>)}</select></label><label><span className="mb-2 block text-sm font-bold">Điểm muốn dùng</span><input type="number" min={0} value={form.pointsToUse} onChange={event=>setForm(current=>({...current,pointsToUse:Number(event.target.value)}))} className="field"/></label></div><label className="mt-4 block"><span className="mb-2 block text-sm font-bold">Ghi chú cho bếp</span><textarea value={form.note} onChange={event=>setForm(current=>({...current,note:event.target.value}))} className="field min-h-24 py-3" maxLength={500}/></label><button onClick={()=>quoteMutation.mutate()} className="button-secondary mt-4" disabled={quoteMutation.isPending}>{quoteMutation.isPending?<LoaderCircle className="animate-spin"/>:'Áp dụng và tính lại'}</button></section>
    </div>
    <aside className="surface h-fit rounded-4xl p-6 lg:sticky lg:top-24"><h2 className="text-xl font-black">Xác nhận đơn</h2>{error&&<p role="alert" className="mt-4 rounded-2xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{quote?<><div className="mt-5 space-y-3">{quote.lines.map((line,index)=><div key={index} className="flex justify-between gap-3 text-sm"><span>{line.quantity}× {line.name}</span><span>{money(line.lineSubtotal)}</span></div>)}</div><div className="my-5 border-t"/><div className="space-y-2 text-sm text-[color:var(--muted)]"><div className="flex justify-between"><span>Tạm tính</span><span>{money(quote.subtotal)}</span></div><div className="flex justify-between"><span>Coupon</span><span>-{money(quote.couponDiscount)}</span></div><div className="flex justify-between"><span>Voucher</span><span>-{money(quote.voucherDiscount)}</span></div><div className="flex justify-between"><span>Điểm</span><span>-{money(quote.pointDiscount)}</span></div></div><div className="mt-4 flex justify-between text-xl font-black"><span>Thanh toán</span><span className="text-brand-600">{money(quote.totalAmount)}</span></div><button onClick={()=>orderMutation.mutate()} disabled={orderMutation.isPending||(form.pickupType==='SCHEDULED'&&!form.scheduledPickupAt)} className="button-primary mt-6 w-full">{orderMutation.isPending?<LoaderCircle className="animate-spin"/>:<><CheckCircle2 size={19}/> Đặt món</>}</button></>:<><p className="mt-4 text-sm leading-6 text-[color:var(--muted)]">Nhấn “Tính tổng đơn” để máy chủ xác nhận giá, ưu đãi, voucher và số điểm.</p><button onClick={()=>quoteMutation.mutate()} className="button-primary mt-6 w-full">Tính tổng đơn</button></>}</aside>
  </div>;
}
