'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CheckCircle2, MessageCircle, Printer, Send, Star, XCircle } from 'lucide-react';
import { QRCodeSVG } from 'qrcode.react';
import { useCallback, useState } from 'react';
import { LoadingState } from '@/components/loading-state';
import { StatusBadge } from '@/components/status-badge';
import { apiRequest, authHeaders, formatDateTime, formatMoney } from '@/lib/api';
import { useAuthStore } from '@/lib/auth-store';
import { useRealtime } from '@/lib/use-realtime';

type Message = { id:string; content:string; senderRole:string; createdAt:string };
type Order = { id:string; orderCode:string; status:string; paymentStatus:string; paymentMethod:string; totalAmount:number; subtotal:number; discountTotal:number; createdAt:string; pickupQrToken?:string; chatRoom?:{id:string}; items:{id:string;productId?:string;productNameSnapshot:string;variantNameSnapshot?:string;quantity:number;lineSubtotal:number}[]; payments:{id:string;qrPayload?:string;status:string}[]; statusHistory:{id:string;newStatus:string;createdAt:string;note?:string}[] };
const orderEvents = ['order:accepted','order:rejected','order:preparing','order:ready','order:completed','order:cancelled','payment:updated'];

export function OrderDetail({ id }: { id:string }) {
  const token=useAuthStore(state=>state.accessToken); const queryClient=useQueryClient();
  const [content,setContent]=useState(''); const [rating,setRating]=useState(5); const [notice,setNotice]=useState('');
  const order=useQuery({queryKey:['order',id],queryFn:()=>apiRequest<Order>(`/orders/${id}`,{headers:authHeaders(token)}),enabled:!!token,refetchInterval:20_000});
  const refresh=useCallback(()=>queryClient.invalidateQueries({queryKey:['order',id]}),[id,queryClient]);
  useRealtime(orderEvents,refresh,id);
  const messages=useQuery({queryKey:['chat',order.data?.chatRoom?.id],queryFn:()=>apiRequest<Message[]>(`/chat/rooms/${order.data?.chatRoom?.id}/messages`,{headers:authHeaders(token)}),enabled:!!token&&!!order.data?.chatRoom?.id,refetchInterval:5000});
  const send=useMutation({mutationFn:()=>apiRequest(`/chat/rooms/${order.data?.chatRoom?.id}/messages`,{method:'POST',headers:authHeaders(token),body:JSON.stringify({content})}),onSuccess:()=>{setContent('');messages.refetch()}});
  const payment=useMutation({mutationFn:()=>apiRequest(`/payments/${id}/mock-vnpay/succeed`,{method:'POST',headers:authHeaders(token)}),onSuccess:()=>{setNotice('Thanh toán VNPay mô phỏng thành công.');refresh()}});
  const cancel=useMutation({mutationFn:()=>apiRequest(`/orders/${id}/cancel`,{method:'POST',headers:authHeaders(token),body:JSON.stringify({reason:'Sinh viên thay đổi nhu cầu'})}),onSuccess:refresh});
  const review=useMutation({mutationFn:(productId:string)=>apiRequest('/reviews',{method:'POST',headers:authHeaders(token),body:JSON.stringify({productId,orderId:id,rating,content:'Món ăn ngon, phục vụ nhanh.'})}),onSuccess:()=>setNotice('Cảm ơn bạn đã đánh giá!')});
  if(order.isLoading||!order.data)return <LoadingState/>;
  const value=order.data; const paymentQr=value.payments.find(item=>item.qrPayload&&item.status==='PENDING')?.qrPayload;
  return <div className="grid gap-6 lg:grid-cols-[1fr_380px]">
    <div className="space-y-6">
      <section className="surface rounded-3xl p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">{value.orderCode}</p><h1 className="mt-2 text-3xl font-black">Chi tiết đơn hàng</h1><p className="mt-2 text-sm text-[color:var(--muted)]">Đặt lúc {formatDateTime(value.createdAt)}</p></div><StatusBadge value={value.status}/></div>{notice&&<p className="mt-4 rounded-2xl bg-brand-50 p-3 text-sm font-bold text-brand-700">{notice}</p>}<div className="mt-7 space-y-5 border-l-2 border-brand-100 pl-6">{value.statusHistory.map((history,index)=><div key={history.id} className="relative"><span className="absolute -left-[31px] top-1 h-4 w-4 rounded-full bg-brand-600 ring-4 ring-brand-50"/><StatusBadge value={history.newStatus}/><p className="mt-1 text-xs text-[color:var(--muted)]">{formatDateTime(history.createdAt)} {history.note&&`· ${history.note}`}</p>{index===value.statusHistory.length-1&&<span className="sr-only">Trạng thái hiện tại</span>}</div>)}</div><div className="mt-6 flex flex-wrap gap-2">{['PENDING','ACCEPTED'].includes(value.status)&&<button onClick={()=>window.confirm('Xác nhận hủy đơn này?')&&cancel.mutate()} className="button-secondary text-red-600"><XCircle size={17}/>Hủy đơn</button>}{value.paymentMethod==='VNPAY_QR_MOCK'&&value.paymentStatus==='PENDING'&&<button onClick={()=>payment.mutate()} className="button-primary"><CheckCircle2 size={17}/>Thanh toán VNPay demo</button>}<button onClick={()=>window.print()} className="button-secondary"><Printer size={17}/>In biên nhận</button></div></section>
      <section className="surface rounded-3xl p-6"><h2 className="text-xl font-black">Món đã đặt</h2><div className="mt-4 divide-y">{value.items.map(item=><div key={item.id} className="flex justify-between gap-4 py-4"><div><p className="font-bold">{item.quantity}× {item.productNameSnapshot}</p><p className="text-sm text-[color:var(--muted)]">{item.variantNameSnapshot??'Tiêu chuẩn'}</p>{value.status==='COMPLETED'&&item.productId&&<div className="mt-2 flex items-center gap-1">{[1,2,3,4,5].map(star=><button key={star} onClick={()=>setRating(star)} aria-label={`${star} sao`}><Star size={17} className={star<=rating?'fill-amber-400 text-amber-400':'text-gray-300'}/></button>)}<button className="ml-2 text-xs font-bold text-brand-600" onClick={()=>review.mutate(item.productId!)}>Gửi đánh giá</button></div>}</div><span className="font-bold">{formatMoney(item.lineSubtotal)}</span></div>)}</div></section>
      {value.chatRoom&&<section className="surface overflow-hidden rounded-3xl"><header className="flex items-center gap-2 border-b p-5"><MessageCircle className="text-brand-600"/><h2 className="font-black">Chat với thu ngân</h2></header><div className="max-h-80 space-y-3 overflow-y-auto p-5">{messages.data?.map(message=><div key={message.id} className={`max-w-[80%] rounded-2xl p-3 ${message.senderRole==='STUDENT'?'ml-auto bg-brand-600 text-white':'bg-brand-50 text-brand-900'}`}><p className="text-sm">{message.content}</p><p className="mt-1 text-[10px] opacity-60">{formatDateTime(message.createdAt)}</p></div>)}</div><div className="flex gap-2 border-t p-4"><input value={content} onChange={event=>setContent(event.target.value)} className="field" placeholder="Nhắn cho thu ngân…"/><button onClick={()=>send.mutate()} disabled={!content} className="button-primary"><Send size={17}/></button></div></section>}
    </div>
    <aside className="space-y-6"><section className="surface rounded-3xl p-6"><h2 className="text-xl font-black">Thanh toán</h2><div className="mt-5 space-y-2 text-sm"><div className="flex justify-between"><span>Tạm tính</span><span>{formatMoney(value.subtotal)}</span></div><div className="flex justify-between text-brand-600"><span>Ưu đãi</span><span>-{formatMoney(value.discountTotal)}</span></div><div className="flex justify-between border-t pt-4 text-xl font-black"><span>Tổng</span><span>{formatMoney(value.totalAmount)}</span></div></div><div className="mt-4 flex justify-between"><span className="text-sm">{value.paymentMethod}</span><StatusBadge value={value.paymentStatus}/></div>{paymentQr&&<div className="mt-5 rounded-2xl bg-white p-4 text-center"><QRCodeSVG value={paymentQr} size={180} className="mx-auto"/><p className="mt-2 text-xs text-slate-600">QR VNPay mô phỏng</p></div>}</section>{value.pickupQrToken&&<section className="surface rounded-3xl p-6 text-center"><p className="eyebrow">Mã nhận món bảo mật</p><div className="mx-auto my-5 w-fit rounded-3xl bg-white p-4"><QRCodeSVG value={value.pickupQrToken} size={210}/></div><p className="text-sm leading-6 text-[color:var(--muted)]">Đưa mã này cho thu ngân khi đơn sẵn sàng. Mã chỉ dùng một lần.</p></section>}</aside>
  </div>;
}
