import { ApiProperty, ApiPropertyOptional, PartialType } from '@nestjs/swagger';
import { EmployeeStatus, Role, ShiftStatus } from '@prisma/client';
import { Type } from 'class-transformer';
import { IsArray, IsDateString, IsEmail, IsEnum, IsInt, IsNumber, IsOptional, IsString, Matches, Min, MinLength, ValidateNested } from 'class-validator';

export class CreateIngredientDto { @ApiProperty() @IsString() name!: string; @ApiProperty() @IsString() unit!: string; @ApiProperty() @Type(() => Number) @IsNumber() @Min(0) currentQuantity!: number; @ApiProperty() @Type(() => Number) @IsNumber() @Min(0) lowStockThreshold!: number; @ApiProperty() @Type(() => Number) @IsNumber() @Min(0) reorderThreshold!: number; @ApiProperty() @Type(() => Number) @IsInt() @Min(0) costPerUnit!: number; }
export class UpdateIngredientDto extends PartialType(CreateIngredientDto) {}
export class AdjustInventoryDto { @ApiProperty() @Type(() => Number) @IsNumber() delta!: number; @ApiProperty() @IsString() @MinLength(3) reason!: string; }
export class CreateSupplierDto { @ApiProperty() @IsString() name!: string; @ApiProperty() @IsString() contactName!: string; @ApiProperty() @IsString() phone!: string; @ApiPropertyOptional() @IsOptional() @IsEmail() email?: string; @ApiProperty() @IsString() address!: string; }
export class UpdateSupplierDto extends PartialType(CreateSupplierDto) {}
export class StockReceiptItemDto { @ApiProperty() @IsString() ingredientId!: string; @ApiProperty() @Type(() => Number) @IsNumber() @Min(0.001) quantity!: number; @ApiProperty() @Type(() => Number) @IsInt() @Min(0) unitCost!: number; }
export class CreateStockReceiptDto { @ApiProperty() @IsString() supplierId!: string; @ApiPropertyOptional({ description: 'Nhân viên nhận hàng; bắt buộc khi quản trị viên không có hồ sơ nhân viên.' }) @IsOptional() @IsString() employeeId?: string; @ApiProperty() @IsDateString() receivedAt!: string; @ApiPropertyOptional() @IsOptional() @IsString() note?: string; @ApiProperty({ type: [StockReceiptItemDto] }) @IsArray() @ValidateNested({ each: true }) @Type(() => StockReceiptItemDto) items!: StockReceiptItemDto[]; }
export class CreateEmployeeDto { @ApiProperty() @IsString() employeeCode!: string; @ApiProperty() @IsString() fullName!: string; @ApiProperty() @IsEmail() email!: string; @ApiPropertyOptional() @IsOptional() @IsString() phone?: string; @ApiProperty({ enum: [Role.CASHIER, Role.KITCHEN_STAFF] }) @IsEnum(Role) workRole!: Role; @ApiProperty() @IsDateString() hireDate!: string; @ApiProperty() @IsString() @MinLength(8) password!: string; }
export class UpdateEmployeeDto extends PartialType(CreateEmployeeDto) { @ApiPropertyOptional({ enum: EmployeeStatus }) @IsOptional() @IsEnum(EmployeeStatus) status?: EmployeeStatus; }
export class CreateShiftDto { @ApiProperty() @IsString() employeeId!: string; @ApiProperty() @IsDateString() date!: string; @ApiProperty({ example: '07:00' }) @Matches(/^([01]\d|2[0-3]):[0-5]\d$/) startTime!: string; @ApiProperty({ example: '15:00' }) @Matches(/^([01]\d|2[0-3]):[0-5]\d$/) endTime!: string; @ApiProperty({ enum: [Role.CASHIER, Role.KITCHEN_STAFF] }) @IsEnum(Role) workRole!: Role; @ApiPropertyOptional() @IsOptional() @IsString() note?: string; }
export class UpdateShiftDto extends PartialType(CreateShiftDto) { @ApiPropertyOptional({ enum: ShiftStatus }) @IsOptional() @IsEnum(ShiftStatus) status?: ShiftStatus; }
export class CorrectAttendanceDto { @ApiPropertyOptional() @IsOptional() @IsDateString() clockInAt?: string; @ApiPropertyOptional() @IsOptional() @IsDateString() clockOutAt?: string; @ApiProperty() @IsString() @MinLength(3) reason!: string; }
