import { HttpStatus, Injectable } from '@nestjs/common';
import { AttendanceStatus, EmployeeStatus, InventoryTransactionType, Prisma, Role, ShiftStatus, StockReceiptStatus, UserStatus } from '@prisma/client';
import * as argon2 from 'argon2';
import { ApiError } from '../../common/api-error';
import { PrismaService } from '../../prisma.service';
import { AdjustInventoryDto, CorrectAttendanceDto, CreateEmployeeDto, CreateIngredientDto, CreateShiftDto, CreateStockReceiptDto, CreateSupplierDto, UpdateEmployeeDto, UpdateIngredientDto, UpdateShiftDto, UpdateSupplierDto } from './operations.dto';

@Injectable()
export class OperationsService {
  constructor(private readonly prisma: PrismaService) {}
  ingredients() { return this.prisma.ingredient.findMany({ orderBy: { name: 'asc' } }); }
  createIngredient(dto: CreateIngredientDto) { return this.prisma.ingredient.create({ data: dto }); }
  updateIngredient(id: string, dto: UpdateIngredientDto) { return this.prisma.ingredient.update({ where: { id }, data: dto }); }
  async deleteIngredient(id: string) { const result = await this.prisma.ingredient.updateMany({ where: { id }, data: { active: false } }); if (!result.count) throw new ApiError(HttpStatus.NOT_FOUND, 'INGREDIENT_NOT_FOUND', 'Không tìm thấy nguyên liệu.'); return { ok: true }; }
  async adjustIngredient(actorUserId: string, id: string, dto: AdjustInventoryDto) { return this.prisma.$transaction(async tx => { const ingredient = await tx.ingredient.findUniqueOrThrow({ where: { id } }); const next = ingredient.currentQuantity.add(dto.delta); if (next.lessThan(ingredient.reservedQuantity) || next.lessThan(0)) throw new ApiError(HttpStatus.CONFLICT, 'INVENTORY_NEGATIVE', 'Điều chỉnh sẽ làm tồn kho khả dụng âm.'); const updated = await tx.ingredient.update({ where: { id }, data: { currentQuantity: next } }); await tx.inventoryTransaction.create({ data: { ingredientId: id, type: InventoryTransactionType.ADJUSTMENT, quantity: new Prisma.Decimal(dto.delta), quantityBefore: ingredient.currentQuantity, quantityAfter: next, reservedBefore: ingredient.reservedQuantity, reservedAfter: ingredient.reservedQuantity, referenceType: 'ADMIN_ADJUSTMENT', referenceId: actorUserId, note: dto.reason } }); await tx.auditLog.create({ data: { actorUserId, action: 'INVENTORY_ADJUSTMENT', entityType: 'Ingredient', entityId: id, beforeData: { currentQuantity: ingredient.currentQuantity.toString() }, afterData: { currentQuantity: next.toString(), reason: dto.reason } } }); return updated; }); }
  suppliers() { return this.prisma.supplier.findMany({ orderBy: { name: 'asc' } }); }
  createSupplier(dto: CreateSupplierDto) { return this.prisma.supplier.create({ data: dto }); }
  updateSupplier(id: string, dto: UpdateSupplierDto) { return this.prisma.supplier.update({ where: { id }, data: dto }); }
  async createReceipt(actorUserId: string, dto: CreateStockReceiptDto) { const actor = await this.prisma.employeeProfile.findUnique({ where: { userId: actorUserId } }); const employee = actor ?? (dto.employeeId ? await this.prisma.employeeProfile.findUnique({ where: { id: dto.employeeId } }) : null); if (!employee) throw new ApiError(HttpStatus.BAD_REQUEST, 'RECEIVING_EMPLOYEE_REQUIRED', 'Vui lòng chọn nhân viên nhận hàng.'); const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Ho_Chi_Minh' }).format(new Date()).replaceAll('-', ''); const count = await this.prisma.stockReceipt.count({ where: { createdAt: { gte: new Date(new Date().setHours(0, 0, 0, 0)) } } }); const receiptCode = `PN-${today}-${String(count + 1).padStart(3, '0')}`; const totalCost = dto.items.reduce((sum, item) => sum + Math.round(item.quantity * item.unitCost), 0); return this.prisma.stockReceipt.create({ data: { receiptCode, supplierId: dto.supplierId, employeeId: employee.id, receivedAt: new Date(dto.receivedAt), note: dto.note, totalCost, items: { create: dto.items.map(item => ({ ingredientId: item.ingredientId, quantity: item.quantity, unitCost: item.unitCost, lineTotal: Math.round(item.quantity * item.unitCost) })) } }, include: { items: true } }); }
  receipts() { return this.prisma.stockReceipt.findMany({ include: { supplier: true, employee: true, items: { include: { ingredient: true } } }, orderBy: { receivedAt: 'desc' } }); }
  async confirmReceipt(actorUserId: string, id: string) { return this.prisma.$transaction(async tx => { const receipt = await tx.stockReceipt.findUnique({ where: { id }, include: { items: { include: { ingredient: true } } } }); if (!receipt || receipt.status !== StockReceiptStatus.DRAFT) throw new ApiError(HttpStatus.CONFLICT, 'STOCK_RECEIPT_ALREADY_CONFIRMED', 'Phiếu nhập không ở trạng thái nháp.'); for (const item of receipt.items) { await tx.ingredient.update({ where: { id: item.ingredientId }, data: { currentQuantity: { increment: item.quantity }, costPerUnit: item.unitCost } }); await tx.inventoryTransaction.create({ data: { ingredientId: item.ingredientId, type: InventoryTransactionType.STOCK_IN, quantity: item.quantity, quantityBefore: item.ingredient.currentQuantity, quantityAfter: item.ingredient.currentQuantity.add(item.quantity), reservedBefore: item.ingredient.reservedQuantity, reservedAfter: item.ingredient.reservedQuantity, referenceType: 'STOCK_RECEIPT', referenceId: receipt.id } }); } const updated = await tx.stockReceipt.update({ where: { id }, data: { status: StockReceiptStatus.CONFIRMED, confirmedAt: new Date() } }); await tx.auditLog.create({ data: { actorUserId, action: 'STOCK_RECEIPT_CONFIRMED', entityType: 'StockReceipt', entityId: id, afterData: { receiptCode: receipt.receiptCode, totalCost: receipt.totalCost } } }); return updated; }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); }

  employees() { return this.prisma.employeeProfile.findMany({ where: { status: EmployeeStatus.ACTIVE }, include: { user: { select: { email: true, status: true, lastLoginAt: true } } }, orderBy: { employeeCode: 'asc' } }); }
  async createEmployee(dto: CreateEmployeeDto) { const allowedRoles: Role[] = [Role.CASHIER, Role.KITCHEN_STAFF]; if (!allowedRoles.includes(dto.workRole)) throw new ApiError(HttpStatus.BAD_REQUEST, 'EMPLOYEE_ROLE_INVALID', 'Vai trò nhân viên không hợp lệ.'); const email = dto.email.trim().toLowerCase(); const passwordHash = await argon2.hash(dto.password); return this.prisma.$transaction(async tx => { const user = await tx.user.create({ data: { email, passwordHash, role: dto.workRole, status: UserStatus.ACTIVE } }); return tx.employeeProfile.create({ data: { userId: user.id, employeeCode: dto.employeeCode, fullName: dto.fullName, phone: dto.phone, workRole: dto.workRole, hireDate: new Date(dto.hireDate), status: EmployeeStatus.ACTIVE }, include: { user: true } }); }); }
  async updateEmployee(id: string, dto: UpdateEmployeeDto) { const allowedRoles: Role[] = [Role.CASHIER, Role.KITCHEN_STAFF]; if (dto.workRole && !allowedRoles.includes(dto.workRole)) throw new ApiError(HttpStatus.BAD_REQUEST, 'EMPLOYEE_ROLE_INVALID', 'Vai trò nhân viên không hợp lệ.'); return this.prisma.$transaction(async tx => { const employee = await tx.employeeProfile.findUnique({ where: { id } }); if (!employee) throw new ApiError(HttpStatus.NOT_FOUND, 'EMPLOYEE_NOT_FOUND', 'Không tìm thấy nhân viên.'); const { email, password, ...profile } = dto; await tx.user.update({ where: { id: employee.userId }, data: { email: email?.trim().toLowerCase(), passwordHash: password ? await argon2.hash(password) : undefined, role: dto.workRole, status: dto.status === EmployeeStatus.ACTIVE ? UserStatus.ACTIVE : dto.status ? UserStatus.INACTIVE : undefined } }); return tx.employeeProfile.update({ where: { id }, data: { ...profile, hireDate: dto.hireDate ? new Date(dto.hireDate) : undefined }, include: { user: true } }); }); }
  async deleteEmployee(id: string) { return this.prisma.$transaction(async tx => { const employee = await tx.employeeProfile.findUnique({ where: { id } }); if (!employee) throw new ApiError(HttpStatus.NOT_FOUND, 'EMPLOYEE_NOT_FOUND', 'Không tìm thấy nhân viên.'); await tx.shift.updateMany({ where: { employeeId: id, status: ShiftStatus.SCHEDULED }, data: { status: ShiftStatus.CANCELLED } }); await tx.refreshToken.updateMany({ where: { userId: employee.userId, revokedAt: null }, data: { revokedAt: new Date() } }); await tx.user.update({ where: { id: employee.userId }, data: { status: UserStatus.INACTIVE } }); return tx.employeeProfile.update({ where: { id }, data: { status: EmployeeStatus.INACTIVE }, include: { user: true } }); }); }
  shifts(employeeId?: string) { return this.prisma.shift.findMany({ where: employeeId ? { employeeId } : {}, include: { employee: true, attendance: true }, orderBy: [{ date: 'asc' }, { startTime: 'asc' }] }); }
  async createShift(dto: CreateShiftDto) { await this.validateShift(dto); return this.prisma.shift.create({ data: { ...dto, date: new Date(dto.date) } }); }
  async updateShift(id: string, dto: UpdateShiftDto) { const current = await this.prisma.shift.findUnique({ where: { id }, include: { attendance: true } }); if (!current) throw new ApiError(HttpStatus.NOT_FOUND, 'SHIFT_NOT_FOUND', 'Không tìm thấy ca làm.'); if (current.attendance) throw new ApiError(HttpStatus.CONFLICT, 'SHIFT_HAS_ATTENDANCE', 'Không thể sửa ca đã có dữ liệu chấm công.'); const merged: CreateShiftDto = { employeeId: dto.employeeId ?? current.employeeId, date: dto.date ?? current.date.toISOString(), startTime: dto.startTime ?? current.startTime, endTime: dto.endTime ?? current.endTime, workRole: dto.workRole ?? current.workRole, note: dto.note ?? current.note ?? undefined }; await this.validateShift(merged, id); return this.prisma.shift.update({ where: { id }, data: { ...dto, date: dto.date ? new Date(dto.date) : undefined } }); }
  async deleteShift(id: string) { const shift = await this.prisma.shift.findUnique({ where: { id }, include: { attendance: true } }); if (!shift) throw new ApiError(HttpStatus.NOT_FOUND, 'SHIFT_NOT_FOUND', 'Không tìm thấy ca làm.'); if (shift.attendance) throw new ApiError(HttpStatus.CONFLICT, 'SHIFT_HAS_ATTENDANCE', 'Không thể xóa ca đã có dữ liệu chấm công.'); await this.prisma.shift.delete({ where: { id } }); return { ok: true }; }
  private async validateShift(dto: CreateShiftDto, excludeId?: string) { if (dto.startTime >= dto.endTime) throw new ApiError(HttpStatus.BAD_REQUEST, 'SHIFT_TIME_INVALID', 'Giờ kết thúc phải sau giờ bắt đầu.'); const employee = await this.prisma.employeeProfile.findUnique({ where: { id: dto.employeeId } }); if (!employee || employee.status !== EmployeeStatus.ACTIVE) throw new ApiError(HttpStatus.BAD_REQUEST, 'EMPLOYEE_NOT_ACTIVE', 'Nhân viên không tồn tại hoặc đã ngừng hoạt động.'); if (employee.workRole !== dto.workRole) throw new ApiError(HttpStatus.BAD_REQUEST, 'SHIFT_ROLE_INVALID', 'Vai trò của ca không khớp với nhân viên.'); const overlap = await this.prisma.shift.findFirst({ where: { ...(excludeId ? { id: { not: excludeId } } : {}), employeeId: dto.employeeId, date: new Date(dto.date), status: { not: ShiftStatus.CANCELLED }, startTime: { lt: dto.endTime }, endTime: { gt: dto.startTime } } }); if (overlap) throw new ApiError(HttpStatus.CONFLICT, 'SHIFT_OVERLAP', 'Nhân viên đã có ca làm trùng thời gian.'); }
  private shiftDateTime(date: Date, time: string) { const [hours, minutes] = time.split(':').map(Number); return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate(), hours - 7, minutes)); }
  async myShifts(userId: string) { const employee = await this.prisma.employeeProfile.findUniqueOrThrow({ where: { userId } }); return this.shifts(employee.id); }
  async clockIn(userId: string) { const employee = await this.prisma.employeeProfile.findUniqueOrThrow({ where: { userId } }); const dateText = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Ho_Chi_Minh' }).format(new Date()); const date = new Date(`${dateText}T00:00:00Z`); const shift = await this.prisma.shift.findFirst({ where: { employeeId: employee.id, date, status: ShiftStatus.SCHEDULED }, orderBy: { startTime: 'asc' } }); if (!shift) throw new ApiError(HttpStatus.NOT_FOUND, 'SHIFT_NOT_FOUND', 'Không tìm thấy ca làm hôm nay.'); const now = new Date(); const scheduledStart = this.shiftDateTime(date, shift.startTime); const scheduledEnd = this.shiftDateTime(date, shift.endTime); return this.prisma.attendance.upsert({ where: { shiftId: shift.id }, update: { clockInAt: now, status: now.getTime() > scheduledStart.getTime() + 5 * 60_000 ? AttendanceStatus.LATE : AttendanceStatus.PRESENT }, create: { employeeId: employee.id, shiftId: shift.id, scheduledStart, scheduledEnd, clockInAt: now, status: now.getTime() > scheduledStart.getTime() + 5 * 60_000 ? AttendanceStatus.LATE : AttendanceStatus.PRESENT } }); }
  async clockOut(userId: string) { const employee = await this.prisma.employeeProfile.findUniqueOrThrow({ where: { userId } }); const attendance = await this.prisma.attendance.findFirst({ where: { employeeId: employee.id, clockInAt: { not: null }, clockOutAt: null }, orderBy: { clockInAt: 'desc' } }); if (!attendance) throw new ApiError(HttpStatus.NOT_FOUND, 'ATTENDANCE_NOT_FOUND', 'Bạn chưa clock in cho ca làm hiện tại.'); const now = new Date(); return this.prisma.attendance.update({ where: { id: attendance.id }, data: { clockOutAt: now, status: now.getTime() < attendance.scheduledEnd.getTime() - 15 * 60_000 ? AttendanceStatus.LEFT_EARLY : attendance.status } }); }
  attendances() { return this.prisma.attendance.findMany({ include: { employee: true, shift: true }, orderBy: { scheduledStart: 'desc' } }); }
  async correctAttendance(actorUserId: string, id: string, dto: CorrectAttendanceDto) { return this.prisma.$transaction(async tx => { const before = await tx.attendance.findUniqueOrThrow({ where: { id } }); const updated = await tx.attendance.update({ where: { id }, data: { clockInAt: dto.clockInAt ? new Date(dto.clockInAt) : undefined, clockOutAt: dto.clockOutAt ? new Date(dto.clockOutAt) : undefined } }); await tx.attendanceAudit.create({ data: { attendanceId: id, actorUserId, beforeData: before as unknown as Prisma.InputJsonValue, afterData: updated as unknown as Prisma.InputJsonValue, reason: dto.reason } }); await tx.auditLog.create({ data: { actorUserId, action: 'ATTENDANCE_CORRECTION', entityType: 'Attendance', entityId: id, beforeData: before as unknown as Prisma.InputJsonValue, afterData: { ...updated, reason: dto.reason } as unknown as Prisma.InputJsonValue } }); return updated; }); }
}
